# standard jekyll configuration
name: "Home of Jason Doyle"
permalink: /articles/:title
encoding: UTF-8
lsi: TRUE
pygments: true
timezone: America/New_York
exclude: ['scss', 'CNAME', '.git','.gitignore', '.DS_Store', 'codekit-config.json']
markdown: rdiscount

# configuration required for some pages
domain: jmd.io
title: Jason Doyle
author: Jason Doyle
email: jasonmackdoyle@gmail.com

# configuration for enhancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
    username: mackdoyle/mackdoyle.github.io
