# -- Standard Jekyll Configuration


name: Home of Jason Doyle
description: Periodic postings of musings and whatever else I feel like writing about.
author:
  name: Jason Doyle
  email: jason@jmd.io
timezone: America/New_York

# -- Site Config
encoding: UTF-8
lsi: TRUE
highlighter: pygments
pygments: true
markdown: rdiscount

# -- Path Config
include: ['_pages']
permalink: 'articles/:title/'
relative_permalinks: false
paginate_path: 'articles:num/'


# -- Configuration required for some pages
domain: jmd.io
title: Jason Doyle
author: Jason Doyle
email: jason@jmd.io


# -- Social handles
social:
  github: mackdoyle
  twitter: mackdoyle1
  codepen: mackdoyle


# -- Github Specific Settings
github:
    username: mackdoyle/mackdoyle.github.io


# -- Google Analytics
account: UA-52530016-1


# Files/Directories to ignore
# -----------------------------------------------------------------
exclude: ['**/*.log', 'tmp', 'src', 'node_modules', 'Gruntfile.js', 'package.json', 'bower.json', 'bower_components', 'codekit-config.json',
          'jmd.sublime-project', 'jmd.sublime-workplace','scss', 'CNAME', '.git','.gitignore', '**.DS_Store', 'codekit-config.json',
          '**.sublime-project', '**.sublime-workspace', '**.UlyssesRoot', '**.Ulysses-Group.plist', 'Gruntfile.js']


# Configuration for enhancements, uncomment to enable
# -----------------------------------------------------------------

# <--------------------------
# Github Style Markdown:
# markdown: redcarpet
# redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#
# redcarpet allows you to replace {% highlight javascript %} with ```javascript
# -------------------------->


